#!/usr/bin/env bash
# brew-formula.sh — render the Homebrew formula for a PUBLISHED hay release.
#
# Every release ends with a formula bump, and the checksums must come from the release itself
# rather than from a local build: the tap installs the exact archives `release-dispatch.yml` produced, so
# anything computed here from a local `cargo build` would be a different binary wearing the same
# version. Each archive is checksum-verified AND provenance-verified before its hash reaches the
# formula — a formula can never be generated from an artifact whose build cannot be proven.
#
#   ./brew-formula.sh v0.2.0 > ../homebrew-tap/Formula/hay.rb
#   ./brew-formula.sh --selftest
#
# Env overrides:
#   HAY_REPO_SLUG   owner/repo the release lives in (default: mneves75/hay)
set -euo pipefail

REPO_SLUG="${HAY_REPO_SLUG:-mneves75/hay}"

# Scratch directory, at file scope on purpose: an EXIT trap runs after the function that declared
# its `local` has returned, so trapping on a local made cleanup fail with "unbound variable" under
# `set -u` — and the script then exited 1 having rendered a perfectly good formula. An exit code
# that lies about work that succeeded is the same defect class this repository catalogues.
WORKDIR=""
cleanup() {
  if [ -n "${WORKDIR:-}" ] && [ -d "$WORKDIR" ]; then
    rm -r -- "$WORKDIR"
  fi
  return 0
}
trap cleanup EXIT

# The four targets Homebrew can install. `release-dispatch.yml` also builds a Windows zip, which brew has
# no use for; if that list ever changes, this one has to change with it deliberately.
MAC_ARM_TARGET="aarch64-apple-darwin"
MAC_INTEL_TARGET="x86_64-apple-darwin"
LINUX_ARM_TARGET="aarch64-unknown-linux-gnu"
LINUX_INTEL_TARGET="x86_64-unknown-linux-gnu"

need() {
  command -v "$1" >/dev/null 2>&1 || { echo "brew-formula: missing '$1' ($2)" >&2; exit 2; }
}

# Every validator matches the WHOLE string with [[ =~ ]]. `printf | grep -E '^...$'` is
# line-based, so a value with an embedded newline passed as long as any one line matched.
valid_repo_slug() {
  [[ "$1" =~ ^[A-Za-z0-9]([A-Za-z0-9-]{0,37}[A-Za-z0-9])?/[A-Za-z0-9][A-Za-z0-9._-]{0,99}$ ]]
}

valid_commit_sha() {
  [[ "$1" =~ ^[0-9a-f]{40}$ ]]
}

valid_stable_tag() {
  [[ "$1" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]
}

require_lightweight_release_tag() {
  [ "$1" = commit ] && valid_commit_sha "$2"
}

source_digest_for_tag() {
  local tag="$1" record object_type source_digest
  record="$(gh api "repos/${REPO_SLUG}/git/ref/tags/${tag}" \
    --jq '[.object.type, .object.sha] | @tsv')" ||
    { echo "brew-formula: could not resolve $tag" >&2; return 2; }
  IFS=$'\t' read -r object_type source_digest <<<"$record"
  require_lightweight_release_tag "$object_type" "$source_digest" ||
    { echo "brew-formula: $tag is not a lightweight tag at a commit" >&2; return 2; }
  printf '%s\n' "$source_digest"
}

sha256_file() {
  shasum -a 256 "$1" | awk '{print $1}'
}

checksum_from_manifest() {
  local manifest="$1" archive="$2" expected_name="$3"
  local line sum count actual
  count="$(awk 'END { print NR }' "$manifest")"
  if [ "$count" != "1" ]; then
    echo "brew-formula: $manifest must contain exactly one checksum record" >&2
    return 2
  fi
  IFS= read -r line <"$manifest" || [ -n "$line" ]
  if ! printf '%s\n' "$line" | grep -Eq '^[0-9a-f]{64}  '; then
    echo "brew-formula: $manifest checksum must be lowercase 64-hex" >&2
    return 2
  fi
  sum="${line%%  *}"
  if [ "$line" != "$sum  $expected_name" ]; then
    echo "brew-formula: $manifest must name exactly $expected_name" >&2
    return 2
  fi
  actual="$(sha256_file "$archive")"
  if [ "$sum" != "$actual" ]; then
    echo "brew-formula: $expected_name checksum mismatch" >&2
    return 2
  fi
  printf '%s\n' "$sum"
}

# Pure rendering, separated from the network so it can be tested offline. Every value it prints is
# an argument: there is no hidden state that a selftest would fail to cover.
render_formula() {
  local version="$1" mac_arm="$2" mac_intel="$3" linux_arm="$4" linux_intel="$5"
  local base="https://github.com/${REPO_SLUG}/releases/download/v${version}"
  cat <<EOF
# typed: false
# frozen_string_literal: true

# Copyright 2026 Marcus Neves
# SPDX-License-Identifier: MIT

# Generated by hay's brew-formula.sh from the published release archives. Do not hand-edit the
# urls or checksums: they are copied from assets whose provenance attestation was verified.
class Hay < Formula
  desc "Ranked grep for coding agents, with the priors ripgrep deliberately lacks"
  homepage "https://github.com/${REPO_SLUG}"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "${base}/hay-v${version}-${MAC_ARM_TARGET}.tar.gz"
      sha256 "${mac_arm}"
    end
    on_intel do
      url "${base}/hay-v${version}-${MAC_INTEL_TARGET}.tar.gz"
      sha256 "${mac_intel}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/hay-v${version}-${LINUX_ARM_TARGET}.tar.gz"
      sha256 "${linux_arm}"
    end
    on_intel do
      url "${base}/hay-v${version}-${LINUX_INTEL_TARGET}.tar.gz"
      sha256 "${linux_intel}"
    end
  end

  def install
    bin.install "hay"
    doc.install "README.md", "CHANGELOG.md", "LICENSE"
  end

  test do
    assert_match "hay #{version}", shell_output("#{bin}/hay --version")

    # The product is the ORDER, so the test asserts the order rather than that the binary runs.
    # Path order would put docs/archive/plan.md first, because "docs" sorts before "src"; hay
    # exists to put the declaration there instead.
    (testpath/"src").mkpath
    (testpath/"docs/archive").mkpath
    (testpath/"src/auth.ts").write("export function validateSession(t) {\n  return t\n}\n")
    (testpath/"docs/archive/plan.md").write("we will call validateSession from the gateway\n")
    output = shell_output("#{bin}/hay -F validateSession .")
    assert_match "src/auth.ts:1:export function validateSession", output.lines.first
    assert_equal 2, output.lines.count

    # Exit 1 is "searched fine, found nothing" — never a failure, and never confused with exit 2.
    shell_output("#{bin}/hay -F no_such_symbol_anywhere .", 1)
  end
end
EOF
}

# Download one release archive, prove it is the artifact the release workflow built, and print its
# sha256. Both checks are load-bearing: the checksum proves the bytes match the release's own
# manifest, the attestation proves that manifest came from the authorized main build rather than from
# someone with write access to the release page.
checksum_of_verified_asset() {
  local tag="$1" target="$2" workdir="$3" source_digest="$4"
  local asset="hay-${tag}-${target}.tar.gz"
  gh release download "$tag" -R "$REPO_SLUG" -p "$asset" -p "$asset.sha256" \
    -D "$workdir" --clobber >&2 ||
    { echo "brew-formula: could not download $asset and its checksum" >&2; return 2; }
  local sum
  sum="$(checksum_from_manifest "$workdir/$asset.sha256" "$workdir/$asset" "$asset")" ||
    return 2
  # The release workflow is loaded from main and refuses unless the tag names that same commit.
  # Requiring both source ref and digest prevents a workflow run on another ref, or another main
  # commit, from lending its provenance to these bytes.
  gh attestation verify "$workdir/$asset" -R "$REPO_SLUG" \
    --signer-workflow "${REPO_SLUG}/.github/workflows/release-dispatch.yml" \
    --source-ref refs/heads/main --source-digest "$source_digest" >/dev/null 2>&1 ||
    { echo "brew-formula: provenance attestation failed for $asset" >&2; return 2; }
  printf '%s\n' "$sum"
}

selftest() {
  local out
  valid_repo_slug "mneves75/hay" || { echo "selftest: real repository slug rejected" >&2; exit 1; }
  valid_repo_slug "owner-name/repo_name.rs" || { echo "selftest: safe repository slug rejected" >&2; exit 1; }
  local good_sha="0123456789abcdef0123456789abcdef01234567"
  require_lightweight_release_tag commit "$good_sha" ||
    { echo "selftest: valid release tag object rejected" >&2; exit 1; }
  if require_lightweight_release_tag tag "$good_sha" ||
    require_lightweight_release_tag commit "${good_sha}0" ||
    require_lightweight_release_tag commit $'0123456789abcdef0123456789abcdef01234567\nx'; then
    echo "selftest: annotated or malformed release tag object admitted" >&2
    exit 1
  fi
  local bad_slug
  # shellcheck disable=SC2016  # hostile literals must stay literal
  for bad_slug in '' owner /repo owner/ 'owner/repo/extra' '../owner/repo' \
    'owner/repo"; system("id"); #' 'owner/repo#{`id`}' 'owner name/repo' $'owner/repo\nx"; #'; do
    if valid_repo_slug "$bad_slug"; then
      echo "selftest: repository slug validation admits '$bad_slug'" >&2
      exit 1
    fi
  done
  out="$(render_formula 9.9.9 aaa bbb ccc ddd)"
  # No explicit `version` stanza: `brew audit --strict` rejects one that repeats what it can scan
  # from the url, and every url here carries the tag. The version must therefore live in the urls,
  # which is what the next two cases check.
  case "$out" in
    *'version "'*) echo "selftest: an explicit version stanza fails brew audit --strict" >&2; exit 1 ;;
  esac
  case "$out" in
    *"hay-v9.9.9-${MAC_ARM_TARGET}.tar.gz"*) ;;
    *) echo "selftest: macOS arm url missing" >&2; exit 1 ;;
  esac
  case "$out" in
    *"hay-v9.9.9-${LINUX_INTEL_TARGET}.tar.gz"*) ;;
    *) echo "selftest: linux intel url missing" >&2; exit 1 ;;
  esac
  # A tag that is not exactly vN.N.N must be refused before it reaches the formula, because it is
  # interpolated into Ruby. These are the shapes an injection would take.
  local bad
  # shellcheck disable=SC2016  # these are hostile literals, not expressions to expand
  for bad in 'v1.0.0"; system("id"); #' 'v1.0.0 #{`id`}' 'main' 'v1' 'v1.0' '../v1.0.0' \
    $'v1.0.0\n"; system("id"); #' $'\nv1.0.0' 'v1.0.0-beta1'; do
    if valid_stable_tag "$bad"; then
      echo "selftest: tag validation admits '$bad'" >&2
      exit 1
    fi
  done
  valid_stable_tag 'v10.20.30' ||
    { echo "selftest: tag validation rejects a real tag" >&2; exit 1; }

  # Four distinct checksums, each landing under its own url: a rendering bug that reused one hash
  # for every platform would install the wrong binary and still pass every other check here.
  local hashes
  hashes="$(printf '%s\n' "$out" | grep -c 'sha256 "')"
  [ "$hashes" = "4" ] || { echo "selftest: expected 4 checksums, got $hashes" >&2; exit 1; }
  case "$out" in
    *'sha256 "aaa"'*'sha256 "bbb"'*'sha256 "ccc"'*'sha256 "ddd"'*) ;;
    *) echo "selftest: checksums are not in target order" >&2; exit 1 ;;
  esac
  # The version the tap installs must be the version the binary reports, or `brew test` passes on
  # a formula that installed something else entirely.
  case "$out" in
    *'assert_match "hay #{version}"'*) ;;
    *) echo "selftest: version assertion missing from the test block" >&2; exit 1 ;;
  esac
  # Cleanup must survive being called with nothing to clean, and must not turn a successful run
  # into a failing exit code — the bug this selftest exists to have caught.
  WORKDIR=""
  cleanup || { echo "selftest: cleanup failed with no scratch directory" >&2; exit 1; }
  WORKDIR="$(mktemp -d "${TMPDIR:-/tmp}/hay-brew-selftest.XXXXXX")"
  cleanup || { echo "selftest: cleanup failed with a scratch directory" >&2; exit 1; }
  if [ -d "$WORKDIR" ]; then
    echo "selftest: scratch directory survived cleanup" >&2
    exit 1
  fi
  WORKDIR=""

  local tmp asset sum
  tmp="$(mktemp -d "${TMPDIR:-/tmp}/hay-brew-checksum.XXXXXX")"
  asset="$tmp/hay-v9.9.9-${MAC_ARM_TARGET}.tar.gz"
  printf 'archive bytes' >"$asset"
  sum="$(sha256_file "$asset")"
  printf '%s  %s\n' "$sum" "$(basename "$asset")" >"$asset.sha256"
  [ "$(checksum_from_manifest "$asset.sha256" "$asset" "$(basename "$asset")")" = "$sum" ] ||
    { echo "selftest: valid checksum manifest rejected" >&2; exit 1; }
  printf '%s  other.tar.gz\n' "$sum" >"$asset.sha256"
  if checksum_from_manifest "$asset.sha256" "$asset" "$(basename "$asset")" >/dev/null 2>&1; then
    echo "selftest: wrong filename accepted" >&2; exit 1
  fi
  printf '%s  %s\n%s  %s\n' "$sum" "$(basename "$asset")" "$sum" extra.tar.gz >"$asset.sha256"
  if checksum_from_manifest "$asset.sha256" "$asset" "$(basename "$asset")" >/dev/null 2>&1; then
    echo "selftest: extra checksum record accepted" >&2; exit 1
  fi
  printf '%s  %s\n' "ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789" "$(basename "$asset")" >"$asset.sha256"
  if checksum_from_manifest "$asset.sha256" "$asset" "$(basename "$asset")" >/dev/null 2>&1; then
    echo "selftest: uppercase checksum accepted" >&2; exit 1
  fi
  printf '%s  %s\n' "$(printf '%064d' 0)" "$(basename "$asset")" >"$asset.sha256"
  if checksum_from_manifest "$asset.sha256" "$asset" "$(basename "$asset")" >/dev/null 2>&1; then
    echo "selftest: checksum mismatch accepted" >&2; exit 1
  fi

  # A checksum failure occurs inside command substitution in production. Bash disables errexit
  # there, so this control must exercise the whole wrapper rather than only the parser.
  gh() { return 0; }
  if checksum_of_verified_asset v9.9.9 "$MAC_ARM_TARGET" "$tmp" "$good_sha" \
    >/dev/null 2>&1; then
    echo "selftest: wrapper swallowed an invalid checksum manifest" >&2
    exit 1
  fi
  unset -f gh
  rm -r "$tmp"

  echo "brew-formula selftest ok"
}

main() {
  if ! valid_repo_slug "$REPO_SLUG"; then
    echo "brew-formula: HAY_REPO_SLUG must be a safe owner/repo slug" >&2
    exit 2
  fi
  if [ "${1:-}" = "--selftest" ]; then
    selftest
    return 0
  fi

  need gh "https://cli.github.com"
  need shasum "coreutils/perl"
  need awk "POSIX awk"

  local tag="${1:-}"
  if [ -z "$tag" ]; then
    tag="$(gh release view -R "$REPO_SLUG" --json tagName -q .tagName)"
  fi
  # Exact shape, not a glob. `v[0-9]*` admits `v1"; system("…")` and every other character that
  # goes on to be interpolated verbatim into Ruby (review finding); the tag reaches the formula's
  # urls and its `#{version}` assertion, so anything but digits and dots is a code-injection
  # vector into the file the tap installs.
  if ! valid_stable_tag "$tag"; then
    echo "brew-formula: expected a published release tag like v0.2.0, got '${tag}'" >&2
    exit 2
  fi
  # A prerelease must never become the formula: the tap is the stable install path.
  local prerelease draft
  prerelease="$(gh release view "$tag" -R "$REPO_SLUG" --json isPrerelease -q .isPrerelease)"
  draft="$(gh release view "$tag" -R "$REPO_SLUG" --json isDraft -q .isDraft)"
  if [ "$prerelease" != "false" ] || [ "$draft" != "false" ]; then
    echo "brew-formula: ${tag} is a draft or prerelease; the tap ships published releases only" >&2
    exit 2
  fi

  WORKDIR="$(mktemp -d "${TMPDIR:-/tmp}/hay-brew.XXXXXX")"

  local source_digest mac_arm mac_intel linux_arm linux_intel
  source_digest="$(source_digest_for_tag "$tag")"
  mac_arm="$(checksum_of_verified_asset "$tag" "$MAC_ARM_TARGET" "$WORKDIR" "$source_digest")"
  mac_intel="$(checksum_of_verified_asset "$tag" "$MAC_INTEL_TARGET" "$WORKDIR" "$source_digest")"
  linux_arm="$(checksum_of_verified_asset "$tag" "$LINUX_ARM_TARGET" "$WORKDIR" "$source_digest")"
  linux_intel="$(checksum_of_verified_asset "$tag" "$LINUX_INTEL_TARGET" "$WORKDIR" "$source_digest")"

  render_formula "${tag#v}" "$mac_arm" "$mac_intel" "$linux_arm" "$linux_intel"
}

main "$@"
