#!/usr/bin/env bash
# brew-formula.sh — render the Homebrew formula for a PUBLISHED hay release.
#
# Every release ends with a formula bump, and the checksums must come from the release itself
# rather than from a local build: the tap installs the exact archives `release.yml` produced, so
# anything computed here from a local `cargo build` would be a different binary wearing the same
# version. Each archive is checksum-verified AND provenance-verified before its hash reaches the
# formula — a formula can never be generated from an artifact whose build cannot be proven.
#
#   ./brew-formula.sh v0.2.0 > ../homebrew-tap/Formula/hay.rb
#   ./brew-formula.sh --selftest
#
# Env overrides:
#   HAY_REPO_SLUG   owner/repo the release lives in (default: mneves75/hay)
set -euo pipefail

REPO_SLUG="${HAY_REPO_SLUG:-mneves75/hay}"

# Scratch directory, at file scope on purpose: an EXIT trap runs after the function that declared
# its `local` has returned, so trapping on a local made cleanup fail with "unbound variable" under
# `set -u` — and the script then exited 1 having rendered a perfectly good formula. An exit code
# that lies about work that succeeded is the same defect class this repository catalogues.
WORKDIR=""
cleanup() {
  if [ -n "${WORKDIR:-}" ] && [ -d "$WORKDIR" ]; then
    rm -r -- "$WORKDIR"
  fi
  return 0
}
trap cleanup EXIT

# The four targets Homebrew can install. `release.yml` also builds a Windows zip, which brew has
# no use for; if that list ever changes, this one has to change with it deliberately.
MAC_ARM_TARGET="aarch64-apple-darwin"
MAC_INTEL_TARGET="x86_64-apple-darwin"
LINUX_ARM_TARGET="aarch64-unknown-linux-gnu"
LINUX_INTEL_TARGET="x86_64-unknown-linux-gnu"

need() {
  command -v "$1" >/dev/null 2>&1 || { echo "brew-formula: missing '$1' ($2)" >&2; exit 2; }
}

# Pure rendering, separated from the network so it can be tested offline. Every value it prints is
# an argument: there is no hidden state that a selftest would fail to cover.
render_formula() {
  local version="$1" mac_arm="$2" mac_intel="$3" linux_arm="$4" linux_intel="$5"
  local base="https://github.com/${REPO_SLUG}/releases/download/v${version}"
  cat <<EOF
# typed: false
# frozen_string_literal: true

# Copyright 2026 Marcus Neves
# SPDX-License-Identifier: MIT

# Generated by hay's brew-formula.sh from the published release archives. Do not hand-edit the
# urls or checksums: they are copied from assets whose provenance attestation was verified.
class Hay < Formula
  desc "Ranked grep for coding agents, with the priors ripgrep deliberately lacks"
  homepage "https://github.com/${REPO_SLUG}"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "${base}/hay-v${version}-${MAC_ARM_TARGET}.tar.gz"
      sha256 "${mac_arm}"
    end
    on_intel do
      url "${base}/hay-v${version}-${MAC_INTEL_TARGET}.tar.gz"
      sha256 "${mac_intel}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/hay-v${version}-${LINUX_ARM_TARGET}.tar.gz"
      sha256 "${linux_arm}"
    end
    on_intel do
      url "${base}/hay-v${version}-${LINUX_INTEL_TARGET}.tar.gz"
      sha256 "${linux_intel}"
    end
  end

  def install
    bin.install "hay"
    doc.install "README.md", "CHANGELOG.md", "LICENSE"
  end

  test do
    assert_match "hay #{version}", shell_output("#{bin}/hay --version")

    # The product is the ORDER, so the test asserts the order rather than that the binary runs.
    # Path order would put docs/archive/plan.md first, because "docs" sorts before "src"; hay
    # exists to put the declaration there instead.
    (testpath/"src").mkpath
    (testpath/"docs/archive").mkpath
    (testpath/"src/auth.ts").write("export function validateSession(t) {\n  return t\n}\n")
    (testpath/"docs/archive/plan.md").write("we will call validateSession from the gateway\n")
    output = shell_output("#{bin}/hay -F validateSession .")
    assert_match "src/auth.ts:1:export function validateSession", output.lines.first
    assert_equal 2, output.lines.count

    # Exit 1 is "searched fine, found nothing" — never a failure, and never confused with exit 2.
    shell_output("#{bin}/hay -F no_such_symbol_anywhere .", 1)
  end
end
EOF
}

# Download one release archive, prove it is the artifact the release workflow built, and print its
# sha256. Both checks are load-bearing: the checksum proves the bytes match the release's own
# manifest, the attestation proves that manifest came from the tagged build rather than from
# someone with write access to the release page.
checksum_of_verified_asset() {
  local tag="$1" target="$2" workdir="$3"
  local asset="hay-${tag}-${target}.tar.gz"
  gh release download "$tag" -R "$REPO_SLUG" -p "$asset" -p "$asset.sha256" \
    -D "$workdir" --clobber >&2
  ( cd "$workdir" && shasum -a 256 -c "$asset.sha256" >&2 )
  gh attestation verify "$workdir/$asset" -R "$REPO_SLUG" >/dev/null 2>&1 ||
    { echo "brew-formula: provenance attestation failed for $asset" >&2; exit 2; }
  awk '{ print $1 }' "$workdir/$asset.sha256"
}

selftest() {
  local out
  out="$(render_formula 9.9.9 aaa bbb ccc ddd)"
  # No explicit `version` stanza: `brew audit --strict` rejects one that repeats what it can scan
  # from the url, and every url here carries the tag. The version must therefore live in the urls,
  # which is what the next two cases check.
  case "$out" in
    *'version "'*) echo "selftest: an explicit version stanza fails brew audit --strict" >&2; exit 1 ;;
  esac
  case "$out" in
    *"hay-v9.9.9-${MAC_ARM_TARGET}.tar.gz"*) ;;
    *) echo "selftest: macOS arm url missing" >&2; exit 1 ;;
  esac
  case "$out" in
    *"hay-v9.9.9-${LINUX_INTEL_TARGET}.tar.gz"*) ;;
    *) echo "selftest: linux intel url missing" >&2; exit 1 ;;
  esac
  # Four distinct checksums, each landing under its own url: a rendering bug that reused one hash
  # for every platform would install the wrong binary and still pass every other check here.
  local hashes
  hashes="$(printf '%s\n' "$out" | grep -c 'sha256 "')"
  [ "$hashes" = "4" ] || { echo "selftest: expected 4 checksums, got $hashes" >&2; exit 1; }
  case "$out" in
    *'sha256 "aaa"'*'sha256 "bbb"'*'sha256 "ccc"'*'sha256 "ddd"'*) ;;
    *) echo "selftest: checksums are not in target order" >&2; exit 1 ;;
  esac
  # The version the tap installs must be the version the binary reports, or `brew test` passes on
  # a formula that installed something else entirely.
  case "$out" in
    *'assert_match "hay #{version}"'*) ;;
    *) echo "selftest: version assertion missing from the test block" >&2; exit 1 ;;
  esac
  # Cleanup must survive being called with nothing to clean, and must not turn a successful run
  # into a failing exit code — the bug this selftest exists to have caught.
  WORKDIR=""
  cleanup || { echo "selftest: cleanup failed with no scratch directory" >&2; exit 1; }
  WORKDIR="$(mktemp -d "${TMPDIR:-/tmp}/hay-brew-selftest.XXXXXX")"
  cleanup || { echo "selftest: cleanup failed with a scratch directory" >&2; exit 1; }
  if [ -d "$WORKDIR" ]; then
    echo "selftest: scratch directory survived cleanup" >&2
    exit 1
  fi
  WORKDIR=""

  echo "brew-formula selftest ok"
}

main() {
  if [ "${1:-}" = "--selftest" ]; then
    selftest
    return 0
  fi

  need gh "https://cli.github.com"
  need shasum "coreutils/perl"
  need awk "POSIX awk"

  local tag="${1:-}"
  if [ -z "$tag" ]; then
    tag="$(gh release view -R "$REPO_SLUG" --json tagName -q .tagName)"
  fi
  case "$tag" in
    v[0-9]*) ;;
    *) echo "brew-formula: expected a published tag like v0.2.0, got '${tag}'" >&2; exit 2 ;;
  esac
  # A prerelease must never become the formula: the tap is the stable install path.
  local prerelease draft
  prerelease="$(gh release view "$tag" -R "$REPO_SLUG" --json isPrerelease -q .isPrerelease)"
  draft="$(gh release view "$tag" -R "$REPO_SLUG" --json isDraft -q .isDraft)"
  if [ "$prerelease" != "false" ] || [ "$draft" != "false" ]; then
    echo "brew-formula: ${tag} is a draft or prerelease; the tap ships published releases only" >&2
    exit 2
  fi

  WORKDIR="$(mktemp -d "${TMPDIR:-/tmp}/hay-brew.XXXXXX")"

  local mac_arm mac_intel linux_arm linux_intel
  mac_arm="$(checksum_of_verified_asset "$tag" "$MAC_ARM_TARGET" "$WORKDIR")"
  mac_intel="$(checksum_of_verified_asset "$tag" "$MAC_INTEL_TARGET" "$WORKDIR")"
  linux_arm="$(checksum_of_verified_asset "$tag" "$LINUX_ARM_TARGET" "$WORKDIR")"
  linux_intel="$(checksum_of_verified_asset "$tag" "$LINUX_INTEL_TARGET" "$WORKDIR")"

  render_formula "${tag#v}" "$mac_arm" "$mac_intel" "$linux_arm" "$linux_intel"
}

main "$@"
